# Este arquivo vai no Streamlit Cloud em Settings > Secrets
# NÃO suba este arquivo para o GitHub!

[supabase]
host     = "db.bjiwnfwoebugtkanvmkx.supabase.co"
port     = 5432
dbname   = "postgres"
user     = "postgres"
password = "SUA_SENHA_DO_SUPABASE_AQUI"
